name: Mi Primer Action
on: [push] # Se activa cada vez que subes algo

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "¡Hola! GitHub Actions está funcionando correctamente."